# Generated by Django 2.1 on 2018-08-19 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_auto_20170826_1201'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='goodscategorybrand',
            table='goods_goodsbrand',
        ),
    ]
